repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        types_or: [ts, tsx, javascript, jsx, json, css, markdown]
  - repo: local
    hooks:
      - id: tsc
        name: TypeScript
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false